account/urls.py
from django.urls import path
from . import views
app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='login'),
]

music_app/urls.py
from django.urls import path
from .import views
from account import views as av

app_name = 'music_app'

urlpatterns = [
    path('', views.song_list, name='song_list'),
    path('tag/<slug:tag_slug>/', views.song_list, name='song_list_by_tag'),
    path('<int:year>/<slug:song>/', views.song_detail, name='song_detail'),
    path('<int:song_id>/', views.song_share, name='song_share'),

]

music_player/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_app.urls', namespace='music_app')),
    path('account/', include('account.urls', namespace='account')),

]

account/models.py
from django.db import models

# Create your models here.

music_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# creating model manager


class HindiManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(lang=Song.Languages.HINDI)
# song model.


class Song(models.Model):
    # adding a status field for language choice
    class Languages(models.TextChoices):
        HINDI = 'H', 'Hindi'
        ENGLISH = 'E', 'English'

    name = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    album = models.CharField(max_length=250)
    singer = models.CharField(max_length=250)
    year = models.IntegerField()
    song_img = models.ImageField(upload_to='images/')
    song_file = models.FileField(upload_to='uploads/')
    publish = models.DateTimeField(default=timezone.now)
    lang = models.CharField(
        max_length=2, choices=Languages.choices, default=Languages.HINDI)

    # default manager
    objects = models.Manager()
    # custom manager
    hindi = HindiManager()
    # adding tag manager
    tags = TaggableManager()

    # defining default sort order(reverse chronological order)from newest to oldest

    class Meta:
        ordering = ['-publish']
        # adding a database index for queries filtering or ordering
        indexes = [models.Index(fields=['-publish']),]

    # adding a canonical url

    def get_absolute_url(self):
        return reverse("music_app:song_detail", args=[self.publish.year, self.slug])

account/forms.py
from django import forms
# creating login form


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

music_app/forms.py
from django import forms


class EmailSongForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm

# user login.


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
        else:
            form = LoginForm()

        return render(request, 'account/login.html', {'fm': form})
    else:
        return render(request, "Bad Request")

music_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Song
from .forms import EmailSongForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
#  display song list .


def song_list(request, tag_slug=None):
    songs = Song.hindi.all()
    # filter songs by tag
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        songs = songs.filter(tags__in=[tag])
    return render(request, "music_app/song/song_list.html", {'songs': songs, 'tag': tag})

# display single song


def song_detail(request, year, song):
    song = get_object_or_404(
        Song,  lang=Song.Languages.HINDI,  publish__year=year, slug=song,)
    # list of similar songs
    song_tags_ids = song.tags.values_list('id', flat=True)
    similar_songs = Song.hindi.filter(
        tags__in=song_tags_ids)\
        .exclude(id=song.id)
    similar_songs = similar_songs.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'music_app/song/song_detail.html', {'song': song, 'similar_songs': similar_songs})

# song share via email


def song_share(request, song_id):
    # retrieve post by id
    song = get_object_or_404(Song,  lang=Song.Languages.HINDI, id=song_id)

    sent = False
    if request.method == 'POST':
        # form was submitted
        form = EmailSongForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            cd = form.cleaned_data
            # .....send email
            song_url = request.build_absolute_uri(song.get_absolute_url())
            subject = f"{cd['name']} recommends you to listen "\
                f"{song.name}"
            message = f"Listen{song.name} at {song_url}\n\n"\
                f"{cd['name']}\'s comments:{cd['comments']}"
            send_mail(subject, message,
                      'anupama13pradhan@gmail.com', [cd['to']])

            sent = True
    else:
        form = EmailSongForm()
    return render(request, 'music_app/song/song_share.html', {'song': song, 'sent': sent, 'form': form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  <div id="header">
    <span class="logo">Bookmarks</span>
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
</body>
</html>

music_app/templates/music_app/base.html
{% load music_app_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}{% endblock title %}
    <link rel="stylesheet" href="{% static 'music_app/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'music_app/css/style.css' %}" />
  </head>
  <body>
    {% include 'music_app/navbar.html' %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          <div id="sidebar">
            <h2>My music</h2>
            <p>This is my blog.
              I've wriiten {% total_songs %} songs so far.
            </p>
            <h3>Latest Songs</h3>
            {% show_latest_songs 3 %}
            <h3>Top Artists</h3>
            {% show_top_artists 3  %} 
          </div>
        </div> 
        <div class="col-10">
          {% block content %}{% endblock content%}
        </div>
      </div>
    </div>
   


    
    

  
  
    

    <script src="{% static 'music_app/js/bootstrap.js' %}"></script>
    <script src="{% static 'music_app/js/jquery.js' %}"></script>
    <script src="{% static 'music_app/js/popper.js' %}"></script>
    <script src="{% static 'music_app/js/style.js' %}"></script>
  </body>
</html>

music_app/templates/music_app/navbar.html
<nav class="navbar navbar-expand-sm navbar-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">LogIn</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Log Out</a>
      </li>
    </ul>
  </div>
</nav>

music_app/templates/music_app/song/latest_songs.html
<ul>
  {% for song in latest_songs %}
  <li>
    <a href="{{song.get_absolute_url}}">{{song.name}}</a>
  </li>
  {% endfor %}
</ul>

music_app/templates/music_app/song/song_detail.html
{% extends 'music_app/base.html' %}
{% block content %}
<div class="row mt-5">
  {% comment %} image column {% endcomment %}
  <div class="col-4">
    <img src="{{song.song_img.url}}" alt="" style="width:20rem">
  </div>
  {% comment %} end of image column {% endcomment %}

 {% comment %} song detail info column {% endcomment %}
    <div class="col-8 mt-4">
      <h4>{{song.name}}</h4>
      <p>Album:{{song.album}}</p>
      <p>Singer:{{song.singer}}</p>
      <p>Release year:{{song.year}}</p>
      <div class="row">
        <div class="col-3">
          <a href="" class="btn btn-primary">Create new playlist</a>
        </div>
        <div class="col-3">
          <a href="" class="btn btn-success">Add to playlist</a>
        </div>
        <div class="col-10 mt-2">
          <a href="" class="btn btn-danger" style="width:20rem">Add to favourite</a>
          
        </div>
      </div>
    </div> 
  {% comment %} song detail info column {% endcomment %} 
  </div>
  {% comment %} similar songs start {% endcomment %}
  <h2 class="mt-4">Similar Songs</h2><hr>
  <div class="row">
    
    {% for song in similar_songs %}
    <div class="col-2">
      <div class="similar">
        <img class="card-img-top" src="{{song.song_img.url}}" alt="Card image cap" style="width:10rem">
        <div class="similar-body">
          <p>
            <a href="{{song.get_absolute_url}}">{{song.name|truncatechars:15}}</a>
          </p>
        </div>
      </div>
    </div>
    {% empty %}
      There are no similar song.
    {% endfor %}
    </div>
  </div>
  {% comment %} similar songs end {% endcomment %}

{% endblock content%}

music_app/templates/music_app/song/song_list.html
{% extends 'music_app/base.html' %}
 {% block content %}

<h2>All Songs</h2>
{% comment %} filtering the tag {% endcomment %}
{% if tag %}
<h2>Songs tagged with "{{tag.name}}" </h2>
{% endif %}
{% comment %} filtering ends here {% endcomment %}
{% comment %} start of row {% endcomment %}
<div class="row p-2">
  {% for songs in songs %}
  {% comment %} start of column {% endcomment %}
  <div class="col-3"> 
    {% comment %} single song content {% endcomment %}
    <div class="list" style="width:12rem;"> 
        <img class="card-img-top" src= "{{songs.song_img.url}}" alt="Card image cap"> 
      {% comment %} song info starts {% endcomment %}
      <div class="list-body"> 
          <a href="{{ songs.get_absolute_url }}">
            <h5 class="list-title mt-2">{{songs.name|truncatechars:15}}</h5> 
          </a> 
          {% comment %} adding tags start {% endcomment %}
          <p class="tags">Tags:
            {% for tag in songs.tags.all %}
              <a href="{% url "music_app:song_list_by_tag" tag.slug  %}">{{tag.name}}</a>
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
          {% comment %} adding tags end {% endcomment %}
          <p class="list-text">{{songs.singer}}</p>
          <a href="" class="btn btn-warning">Play</a> 
          <a href="{% url 'music_app:song_share' songs.id %}" class="btn btn-success">Share</a>
      </div> 
      {% comment %} song info ends {% endcomment %}
    </div> 
  {% comment %} single song content ends {% endcomment %}
  </div>
  {% comment %} end of column {% endcomment %}
  {% endfor %}
</div>
{% comment %} end of row  {% endcomment %}

{% endblock content %}

music_app/templates/music_app/song/song_share.html
{% extends 'music_app/base.html' %}


{% block content %}
{% if sent %}
<h1>Email sent successfully!</h1>
<p>{{song.name}} was successfully sent to {{form.cleaned_data.to}}.</p>
{% else %}
<h1>Share '"{{song.name}}" by email</h1>
<form action="" method="POST">
   {% csrf_token %}
   {{form.as_p}}
   <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock content %}

music_app/templates/music_app/song/top_artists.html
<ul>
  {% for song in top_artists %}
  <li>
    <a href="{{song.get_absolute_url}}">{{song.singer}}</a>
  </li>
  {% endfor %}
</ul>

music_app/templates/song/song_list.html
{% extends 'music_app/base.html' %}
 {% block content %}

<h2>All Songs</h2>
{% comment %} start of row {% endcomment %}
<div class="row p-2">
  {% for songs in songs %}
  {% comment %} start of column {% endcomment %}
  <div class="col-3"> 
    {% comment %} single song content {% endcomment %}
    <div class="list" style="width:12rem;"> 
        <img class="card-img-top" src= "{{songs.song_img.url}}" alt="Card image cap"> 
      {% comment %} song info starts {% endcomment %}
      <div class="list-body"> 
          <h5 class="list-title mt-2">{{songs.name}}</h5> 
          <p class="list-text">{{songs.singer}}</p>
          <a href="" class="btn btn-warning">Play</a> 
          <a href="" class="btn btn-success">Share</a>
      </div> 
      {% comment %} song info ends {% endcomment %}
    </div> 
  {% comment %} single song content ends {% endcomment %}
  </div>
  {% comment %} end of column {% endcomment %}
  {% endfor %}
</div>
{% comment %} end of row  {% endcomment %}

{% endblock content %}